version: '3.4'

services:

  web:
    image: ${IMAGE_WEB} 
    restart: always
    environment:
      - CHECK_IN_IPS=${CHECK_IN_IPS}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_SERVE_STATIC_FILES=remove_this_line_when_you_want_a_web_server_to_do_the_file_serving
      - SECRET_KEY_BASE=${RAILS_SECRET_KEY_BASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${EXPOSED_PORT_WEB}:${RAILS_PORT}"
    depends_on:
      - db
 
  db:
    image: ${IMAGE_DB}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${EXPOSED_PORT_DB}:${DB_PORT}"
    volumes:
      - ${PWD:-.}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${DB_DIR}:/var/lib/postgresql/data


